### ISSUE TITLE
Can you elaborate on what this FreeCAD related repo does?

### ISSUE THREAD

**Issue by luzpaz** [TemptorSent/overlay-freecad-kit#1]
Thank you!

**Comment by TemptorSent** [comment]
This repo will be providing a profile and ebuilds for building FreeCAD and related packages on Funtoo.

**Comment by TemptorSent** [comment]
This repo will be providing a profile and ebuilds for building various versions FreeCAD and related packages on Funtoo.

**Comment by luzpaz** [comment]
Thanks!
